In [5]:
import pandas as pd

master_df = pd.read_csv('/content/merged_satellite_dataset.csv')


rain = pd.read_csv('/content/AgriAstra_Rainfall.csv')

rain.head()

,system:index,precipitation,.geo
0,0,20.475891,"{""geodesic"":false,""type"":""Point"",""coordinates""..."
1,1,18.696184,"{""geodesic"":false,""type"":""Point"",""coordinates""..."
2,2,18.696184,"{""geodesic"":false,""type"":""Point"",""coordinates""..."
3,3,20.475891,"{""geodesic"":false,""type"":""Point"",""coordinates""..."
4,4,18.696184,"{""geodesic"":false,""type"":""Point"",""coordinates""..."

In [2]:
rain.columns

Index(['system:index', 'precipitation', '.geo'], dtype='object')

In [3]:
rain.shape

(13, 3)

In [4]:
rain['precipitation'].describe()

count    13.000000
mean     18.531933
std       1.095681
min      17.325289
25%      17.709779
50%      18.696184
75%      18.696184
max      20.475891
Name: precipitation, dtype: float64

In [6]:
avg_rain = rain['precipitation'].mean()

master_df['Rainfall'] = avg_rain

master_df.head()

       NDVI      NDWI         VH         VV   Rainfall
0  0.348767 -0.476177 -20.025476 -12.354627  18.531933
1  0.641812 -0.498966 -17.326365  -9.763876  18.531933
2  0.826490 -0.700789 -18.558639 -11.072210  18.531933
3  0.778754 -0.679737 -19.862415 -10.367734  18.531933
4  0.401090 -0.466092 -19.174761 -12.459310  18.531933

In [7]:
master_df.to_csv(
    'final_agriastra_dataset.csv',
    index=False
)

print("Final dataset created.")

Final dataset created.